Mission7/Components/CartSummaryViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Mission7.Models;

namespace Mission7.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService) {
            cart = cartService;
        }

        //this sends the info for the cart to the Views/Shared/Components/CartSummary/Default.cshtml
        public IViewComponentResult Invoke() {
            return View(cart);
            //return RedirectToPage("/cart");
        }
    }
}

Mission7/Components/TypesViewComponent.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Mission7.Models;

namespace Mission7.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent(IBookstoreRepository temp) => repo = temp;

        //this function here gets all the book categories and does a distinct for all of them
        public IViewComponentResult Invoke()
        {
            ViewBag.BookCategory = RouteData.Values["bookCategory"];
            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Mission7/Views/Shared/BookInfo.cshtml
@*This page displays the info for each book*@ 
@{
}
@model Book
<div class="col-6 text-center">
    <div class="card card-outline-primary m-1 p-1">
        <div class="bg-light p-1">
            <h2>@Model.Title</h2>
            <span class="badge bg-info" style="float:right;">
                @*this form lets a user add a book to cart*@ 
                <form method="post" asp-page="/Cart">
                    <input type="hidden" asp-for="@Model.BookId" />
                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                    <button type="submit" class="btn ">Add</button>
                </form>
            </span>
        </div>
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th>Author</th>
                    <td>@Model.Author</td>
                </tr>
                <tr>
                    <th>ISBN</th>
                    <td>@Model.Isbn</td>
                </tr>
                <tr>
                    <th>Publisher</th>
                    <td>@Model.Publisher</td>
                </tr>
                <tr>
                    <th>Classification</th>
                    <td>@Model.Classification</td>
                </tr>
                <tr>
                    <th>Cateogry</th>
                    <td>@Model.Category</td>
                </tr>
                <tr>
                    <th>Page Count</th>
                    <td>@Model.PageCount</td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td>$@Model.Price</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

Mission7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    @*header info*@ 
    <header>
        <div class="bg-dark text-white p-2">
            <div class="container-fluid">
                <div class="row">
                   
                    <div class="col">
                        <a class="navbar-brand" style="color:white;"  asp-area="" asp-controller="Home" asp-action="Index"
                        asp-route-bookCategory="" asp-route-pageNum="1">Book Store</a>
                    </div>
                    <div class="col-6 text-right">
                        <vc:cart-summary />
                    </div>
                </div>
            </div>
        </div>
        <!--<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">-->
                    @*<ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home"
                               asp-action="Index" asp-route-bookCategory="" asp-route-pageNum="1">Home</a>
                        </li>

                    </ul>*@
                <!--</div>
            </div>
        </nav>-->
    </header>

    <div class="row m-1 p-1">
        @*this div gets all the buttons for the categories*@
        <div class="col-2">
            <h5 class="text-center">Categories</h5>
            <vc:types></vc:types>
        </div>
        @*this div renders teh body*@ 
        <div class="col-10">
            <div class="container">
                @RenderBody()
            </div>
        </div>
    </div>

    @*footer below*@ 
    <br />
    <footer class="border-top footer text-muted text-center">
        <br />
        <p>&copy; 2022 - My Book Store</p>
        <br />
    </footer>

    <script href="/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
</body>
</html>