Mission7/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Mission7.Models
{
    public class Cart
    {
        public List<CartItem> Books { get; set; } = new List<CartItem>();

        public virtual void AddBook(Book bk, int qty)
        {
            CartItem line = Books
                .Where(b => b.Book.BookId == bk.BookId)
                .FirstOrDefault();

            //make sure that if book is already in cart it doest add it again. Just updates quantity 
            if(line == null)
            {
                Books.Add(new CartItem
                {
                    Book = bk,
                    Quantity = qty
                });
            }
            else
            {
                line.Quantity += qty;
            }
        }

        public virtual void RemoveItem(Book bk)
        {
            Books.RemoveAll(b => b.Book.BookId == bk.BookId);
        }

        public virtual void ClearCart()
        {
            Books.Clear();
        }
        //this function gets the total amount for all the books in the cart
        public double GetTotal()
        {
            double sum = Books.Sum(b => b.Quantity * b.Book.Price);
            return sum;
        }
    }


    //this class is the info we need to store about
    //each book in the cart
    public class CartItem
    {
        [Key] 
        public int ItemID { get; set; }
        public Book Book { get; set; }
        public int Quantity { get; set; }
        
    }
}

Mission7/Components/CartSummaryViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Mission7.Models;

namespace Mission7.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService) {
            cart = cartService;
        }

        //this sends the info for the cart to the Views/Shared/Components/CartSummary/Default.cshtml
        public IViewComponentResult Invoke() {
            return View(cart);
            //return RedirectToPage("/cart");
        }
    }
}

Mission7/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission7.Models;
using Mission7.Models.ViewModels;

namespace Mission7.Controllers
{
    public class CheckoutController : Controller
    {
        //before using repository pattern make sure to add it to the startup.cs file
        private ICheckoutRepository repo { get; set; }
        private Cart cart { get; set; }

        //constructor 
        public CheckoutController(ICheckoutRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        //checkout get method
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Checkout());
        }

        //checkout posst method
        [HttpPost]
        public IActionResult Checkout(Checkout checkout)
        {
            //make sure the cart has books in it
            if(cart.Books.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry Your Cart is Empty");
            }

            //check to make sure the form is valid 
            if (ModelState.IsValid)
            {
                checkout.Items = cart.Books.ToArray();
                repo.SavePurchase(checkout);
                cart.ClearCart();
                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }
            
        }
    }
}

Mission7/Pages/Cart.cshtml.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission7.Infastructure;
using Mission7.Models;

namespace Mission7.Pages
{
    public class CartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }
        public Cart cart { get; set; }
        public string ReturnUrl { get; set; }

        //this gets the info about the Books 
        public CartModel(IBookstoreRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        

        //get method for a cart
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        //post method on a cart
        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(b => b.BookId == bookId);
           
            cart.AddBook(b, 1);
           
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            //pass the book to the removeitem;
            cart.RemoveItem(cart.Books.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Mission7/Pages/Cart.cshtml
@page
@model Mission7.Pages.CartModel
@{
}
<h1>My Cart</h1>
<br />
<table class="table table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    @*body contains info about each book added to cart*@ 
    <tbody>
        @foreach (var i in Model.cart.Books)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>$@i.Book.Price.ToString("#,##0.00")</td>
                <td>$@((i.Book.Price * i.Quantity).ToString("#,##0.00")) </td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                    </form>
                </td>
            </tr>
        }

    </tbody>

    @*this contains the info about the total for all the books*@
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>$@Model.cart.GetTotal().ToString("#,##0.00")</td>
           
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-large btn-secondary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-large btn-primary" asp-controller="Checkout" asp-action="Checkout">Checkout</a>
</div>

Mission7/Pages/PurchaseCompleted.cshtml
@page
@{
}
@*this page is the page that lets a user know the purchase is complete*@
<div class="text-center">
    <h2>Purchase Complete</h2>
    <br />
    <a class="btn btn-primary" asp-controller="Home"
       asp-action="Index" asp-route-bookCategory="" asp-route-pageNum="1">Home</a>
</div>

Mission7/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="bg-dark text-white p-2">
            <div class="container-fluid">
                <div class="row">

                    <div class="col">
                        <a class="navbar-brand" style="color:white;" asp-area="" asp-controller="Home" asp-action="Index"
                           asp-route-bookCategory="" asp-route-pageNum="1">Book Store</a>
                    </div>
                    @*<div class="col-6 text-right">
                        <vc:cart-summary />
                    </div>*@
                </div>
            </div>
        </div>
    </header>


    <div class="row m-1 p-1">
        <div class="col-12">
            <div class="container">
                @RenderBody()
            </div>
        </div>
    </div>


    <br />
    <footer class="border-top footer text-muted text-center">
        <br />
        <p>&copy; 2022 - My Book Store</p>
        <br />
    </footer>

    <script href="/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
</body>
</html>